#!/bin/bash

IMAGE="${IMAGE_NAME}:${VERSION}-${VARIANT:-ubuntu}"

# Docker Registry
echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin && \
docker push $DOCKER_USERNAME/$IMAGE


# Bintray's Docker Registry 
echo "${BINTRAY_API_KEY}" | docker login -u "${DOCKER_USERNAME}" --password-stdin $BINTRAY_REPO && \
docker push $BINTRAY_REPO/$IMAGE