#!/bin/bash

IMAGE="${IMAGE_NAME}:${VERSION}-${VARIANT:-ubuntu}"

# Docker Registry
echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin && \
docker push $DOCKER_USERNAME/$IMAGE


# Bintray's Docker Registry 
echo "${BINTRAY_API_KEY}" | docker login -u "${DOCKER_USERNAME}" --password-stdin rishabh9-docker-registry.bintray.io && \
docker push rishabh9-docker-registry.bintray.io/$IMAGE